### ISSUE TITLE
Relicense under the LGPL 3.0 and add Classpath exception

### ISSUE THREAD

**Issue by ComradeNapCali** [SonicMastr/Pigs-In-A-Blanket#9]
Currently, Pigs in a Blanket uses the [regular GPL 3.0 license](https://github.com/SonicMastr/Pigs-In-A-Blanket/blob/master/LICENSE).

However, it would make more sense to use the [LGPL 3.0 license](https://www.gnu.org/licenses/lgpl-3.0.en.html).
This would allow more projects, open and closed to use the library, without having to relicense to the GPL.

In addition, [vitaGL](https://github.com/Rinnegatamante/vitaGL), a similar library to this, is [licensed under the LGPL](https://github.com/Rinnegatamante/vitaGL/blob/master/COPYING).

It would also make sense to include the [Classpath exception](https://www.gnu.org/software/classpath/license.html):
```
Linking this library statically or dynamically with other modules is making a combined work based on this library. Thus, the terms and conditions of the GNU Lesser General Public License cover the whole combination.

As a special exception, the copyright holders of this library give you permission to link this library with independent modules to produce an executable, regardless of the license terms of these independent modules, and to copy and distribute the resulting executable under terms of your choice, provided that you also meet, for each linked independent module, the terms and conditions of the license of that module. An independent module is a module which is not derived from or based on this library. If you modify this library, you may extend this exception to your version of the library, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.
```
This would allow the library to be statically linked to non-(L)GPL projects as long as no modifications where made to the library code itself.

**Comment by SonicMastr** [comment]
I have also been talking to my peers about this and this will be the licensing of the PIB library in a coming update.

Thank you for the extra information as I was already wanting to change the licensing to better suit other projects as well.

**Comment by ComradeNapCali** [comment]
That's great to hear! This will definitely make this more attractive to developers.
Thanks once again!
